const findQAs = (v1)=>{
    const ans = {
        personalQA:[{}],
        socialQA:[{}],
        academincQA:[{}],
        occupationalQA:[{}],
        recreationalQA:[{}],
    }
    if(v1 == "preprimary"){
        ans.personalQA = [{question:"Chews and swallows solid food when placed in his mouth",answer:"NA"},
            {question:"Holds and drinks water or milk or juice from a glass or cup",answer:"NA"},
            {question:"Eats by self with fingers when food is mixed and given",answer:"NA"},
            {question:"Sits on potty or squats to pass urine or stools",answer:"NA"},
            {question:"Indicates verbally or through gestures the need to go to the toilet",answer:"NA"},
            {question:"Takes off under clothes to use toilet (when unbuttoned/ pulling clastic pants)",answer:"NA"},
            {question:"Brushes teeth either with tooth brush or with a finger using tooth paste or tooth powder",answer:"NA"},
            {question:"Cooperates while being bathed extending hands/legs when told",answer:"NA"},
            {question:"Takes off clothes (inlcuding under garments) when unbuttoned",answer:"NA"},
            {question:"Wears undergarments",answer:"NA"},
            {question:"Cleans nose with a handkerchief",answer:"NA"},
            {question:"Washes hands before eating snacks or food or after using toilet or when hands are dirty",answer:"NA"},
            {question:"Wipes with a towel after bath",answer:"NA"},
            {question:"Peels off fruits such as orange and banana before eating",answer:"NA"},
            {question:"Eats with an appropriate side dish such as bread & jam, chapati & curry, Idli & chutncy",answer:"NA"},
            {question:"Mixes and eats by self without spilling",answer:"NA"},
            {question:"Wipes hand and mouth with a towel after washing",answer:"NA"},
            {question:"Wears slippers",answer:"NA"},
            {question:"Wears shoes without shoe lace or buckle",answer:"NA"}]
        ans.socialQA = [{question:"Moves head or eyes to see persons moving near him or in the room",answer:"NA"},
            {question:"Responds to his name by stopping an activity or looking at the person when called",answer:"NA"},
            {question:"Goes to a familiar person when asked to come near him",answer:"NA"},
            {question:"Smiles when other person smiles at him",answer:"NA"},
            {question:"Plays with two other children cooperatively",answer:"NA"},
            {question:"Waits for his turn in the classroom, play ground, dining room",answer:"NA"},
            {question:"Shares his things (pencil, books, eraser, toys and eatables) when requested by his classmates or others",answer:"NA"},
            {question:"Greets teachers or elders in school or at home",answer:"NA"},
            {question:"Differentiates strangers from familiar people",answer:"NA"},
            {question:"Expresses anger displeasure by vocalizations (shouting/turning away/ screaming) other than crying",answer:"NA"},
            {question:"Stops momentarily an activity when said 'no'",answer:"NA"},
            {question:"Uses vocal sounds/gestures/actions to call a person/to get attention of others",answer:"NA"},
            {question:"Responds appropriately to words alongwith gestures such as come, up, go, bye-bye, etc",answer:"NA"},
            {question:"Uses gestures such as shaking head for 'no', head nodding for 'yes' hand gesture for 'come', 'give', 'sleep', 'tata'",answer:"NA"},
            {question:"Follows simple verbal requests with gestures such as 'give', 'I will take' (response could be gestural or verbal)",answer:"NA"},
            {question:"Uses words such as 'mama', 'nana', 'deedi', 'bow bow', etc",answer:"NA"},
            {question:"Follows simple commands without gestures like 'where is the ball', 'put that down', 'bring the ball",answer:"NA"},
            {question:"Answers questions such as 'how does a car go', 'how does an aeroplane go', 'how do you apply face powder', (responses inmiming fashion)",answer:"NA"},
            {question:"Identifies persons by pointing or naming upon request (eg, uncle, aunty, sister, brother, etc.)",answer:"NA"},
            {question:"Asks for desired objects using gestures/alongwith vocalizations",answer:"NA"},
            {question:"Tells him name when asked",answer:"NA"},
            {question:"Gestures/says suitably for Namaste/salam/good morning",answer:"NA"}] 
        ans.academincQA = [
            {question:"Points/shows body parts (head, nose, cycs, cars, hands, legs) when requested.",answer:"NA"},
            {question:"Names body parts when pointed to",answer:"NA"},
            {question:"Paints to 10 comman objects with which he has to interact in his/her home environment (eg.rice, dall, chapati, light, fan, mat, table, chair, shirt/frock, shorts/pants,etc.), when asked or when he wants",answer:"NA"},
            {question:"Says orally the names of the 10 common objects when shown when he wants.",answer:"NA"},
            {question:"Holds pencil and scribbles",answer:"NA"},
            {question:"Colours with a crayon within a given diagram",answer:"NA"},
            {question:"Traces on the given diagram",answer:"NA"},
            {question:"Cooperates while being bathed extending hands/legs when told",answer:"NA"},
            {question:"Copics a given figure/diagram",answer:"NA"},
            {question:"Groups common colours (red, green, blur, yellow) when given a group of coloured objects",answer:"NA"},
            {question:"Groups objects according to the size (big and small, long and short)",answer:"NA"},
            {question:"Gives objects/pictures of common colours when asked",answer:"NA"},
            {question:"Names common colours. (red, green, blue, yellow)",answer:"NA"},
            {question:"Points to the objects which are big and small/long and short upon request",answer:"NA"},
            {question:"Tells the size of the ohjeets (big & small, long & short)",answer:"NA"},
            {question:"Points to sets of objects to show more/less quantity",answer:"NA"},
            {question:"Tells which set has moreless quantity",answer:"NA"},
            {question:"Points to containers with either solids/liquids to show full and empty",answer:"NA"},
            {question:"Fells when a container is shown cither full or empty with or without liquid or solid",answer:"NA"},
            {question:"Rete counis upto 5",answer:"NA"},
            {question:"Counts and gives objects upto 5 when not asked sequentially",answer:"NA"},
            {question:"Counts and gives objects upto 10 when not asked sequentially.",answer:"NA"},
            {question:"Shows a numeral and places value when not asked sequentially",answer:"NA"},
            {question:"Names upto 5 numbers when not asked sequentially",answer:"NA"},
            {question:"Writes numerals upto 5 in a sequence",answer:"NA"},
            {question:"Writes numerals upto 5 when given dictation not sequentially",answer:"NA"},
            {question:"Points to alphabets (English/regional language) on a chart not asked sequentially (3 letter words in case of sight word icaching)",answer:"NA"},
            {question:"Names alphabets when asked not sequentially (3 letter words in case of sight word teaching)",answer:"NA"},
            {question:"Writes alphabets when given dictation (3 letter words in case of sight word teaching)",answer:"NA"},
            {question:"Identifies a clock or wrist watch",answer:"NA"},
            {question:"Tells points to when asked the use of clock or wrist watch",answer:"NA"},
            {question:"Differentiates money from other objects",answer:"NA"},
            {question:"Tells points to when asked the use of money",answer:"NA"},
            {question:"Groups Rs. 1, 2, 5 notes when given",answer:"NA"},
            {question:"Grck 1, 2, 5 rupee notes when asked",answer:"NA"},
            {question:"Points/tells when asked by showing Rs.1, 2, 5 notes",answer:"NA"},
            {question:"Counts and gives 1 rupee notes upto Rs.5 when asked",answer:"NA"},
            {question:"Points to atleast 5 pictures of animals when asked)",answer:"NA"},
            {question:"Names atleast 5 animals when shown pictures",answer:"NA"},
            {question:"Points to atleast 5 pictures of fruits when asked",answer:"NA"},
            {question:"Names atleast 5 fruits when shown pictures",answer:"NA"},
            {question:"Tells/points to the clothes (frock, shorts, shirt, T-shirt)he/she wears when asked",answer:"NA"},
            {question:"Uses words or gestures for 'now and later when necessary",answer:"NA"},
            {question:"Identifies/Names the various means of transport (cycle, auto, cycle rikshaw, bus, car, lorry, acroplane, train)",answer:"NA"},]
        ans.occupationalQA = [
            {question:"Dusts with a duster the furniture in the classroom and home",answer:"NA"},
            {question:"Washes glasses and plates before and after meals.",answer:"NA"},
            {question:"Wipes glasses and plates with a cloth after washing",answer:"NA"},
            {question:"Folds small clothes (such as hand towel/panties).",answer:"NA"}]
        ans.recreationalQA = [{question:"Watches T.V.Advertisements(indoor)",answer:"C"},
            {question:"Dances/claps/taps with rhythm of music in Radio or T.V. (indoor)",answer:"C"},
            {question:"Plays with block assembling and dismantling (indoor)",answer:"C"},
            {question:"Colours with pencils or crayons (indoor)",answer:"C"},
            {question:"Plays make believe games pretending to be teacher, mummy, daddy or elder sibling going to school/household keeping (indoor)",answer:"C"},
            {question:"Arranges own things in their appropriate places, in a given room (indoor)",answer:"C"},
            {question:"Brushes teeth either with tooth brush or with a finger using tooth paste or tooth powder (indoor)",answer:"C"},
            {question:"Sees pictures in magazines without tearing the book (indoor)",answer:"C"},//Sees pictures in magazines without tearing the book
            {question:"Plays with ball",answer:"C"},
            {question:"Plays running and catching game/runs a race/duck walking/frog jumping, etc",answer:"C"},
            {question:"Climbs jungle gym etc",answer:"C"},
            {question:"Sand play",answer:"C"},
            {question:"Water play",answer:"C"},
            {question:"Plays hide and seek game/passing the parcel/musical chairs, etc",answer:"C"},
            {question:"Plays on a slide",answer:"C"},
            {question:"Swings on a swing",answer:"C"}]
    }
    console.log(ans)
    return ans
}

module.exports = findQAs